fixtures:
  repositories:
    stdlib:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:  "https://github.com/voxpupuli/puppet-extlib.git"
    apache:  "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:  "https://github.com/puppetlabs/puppetlabs-concat.git"
    mongodb: "https://github.com/voxpupuli/puppet-mongodb.git"
    qpid:    "https://github.com/theforeman/puppet-qpid.git"
    squid:   "https://github.com/voxpupuli/puppet-squid.git"
    systemd: 'https://github.com/camptocamp/puppet-systemd.git'
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
