fixtures:
  repositories:
    stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:
      repo: 'git://github.com/puppet-community/puppet-extlib'
      ref:  'v0.11.3'
    apache:  "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref:  '2.2.1'
    mongodb: "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    qpid:    "git://github.com/katello/puppet-qpid.git"
    squid3:  "git://github.com/thias/puppet-squid3.git"
  symlinks:
    pulp: "#{source_dir}"
