fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo:   "git://github.com/puppetlabs/puppetlabs-concat"
      branch: "1.2.x"
    concat_native: "git://github.com/theforeman/puppet-concat"
    mongodb:       "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    qpid:          "git://github.com/katello/puppet-qpid.git"
  symlinks:
    pulp: "#{source_dir}"
