fixtures:
  repositories:
    stdlib:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:  "https://github.com/puppet-community/puppet-extlib"
    apache:  "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:  "https://github.com/puppetlabs/puppetlabs-concat.git"
    mongodb: "https://github.com/puppetlabs/puppetlabs-mongodb.git"
    qpid:    "https://github.com/theforeman/puppet-qpid.git"
    squid3:  "https://github.com/thias/puppet-squid3.git"
  symlinks:
    pulp: "#{source_dir}"
